version: "3"
services:
  client:
    build:
      context: ../client
      dockerfile: ../docker/client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app

  server:
    build:
      context: ../server
      dockerfile: ../docker/server/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ../server:/app
    environment:
      - PORT=3001
      - HOSTNAME="localhost"
      - ORIGIN_WEBSITE="http://localhost:5173"
      - DB="mongodb://localhost:27017/wisp"
      - SALT=10
      - JWT_PRIVATE_TOKEN="supersecureandlongsecretkeyforwispapp2024$%^&!"
      - EMAIL='help.wisp@gmail.com'
      - PASSWORD='rwmprundchjunljb
